version: "3.8"
services:
  db:
    image: postgres:13
    volumes:
      - ./scripts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rinha}
      POSTGRES_USER: ${DB_USER:-rinha}
      POSTGRES_DB: ${DB_NAME:-rinha_db}
    ports:
      - "5422:5432"
    restart: always